Repository WeCodeEs/CuckoApp, pull requests merged in 2024-11, with the labels that each got.

#21 Weck 19 historial pedidos
  .expo/types/router.d.ts
  app/(drawer)/_layout.tsx
  app/(drawer)/orderHistory.tsx
  app/(drawer)/order_details.tsx
  app/(tabs)/cart.tsx
  constants/Colors.ts
Labels: enhancement

#26 WECK-28: Recover CuckoTheme.
  app/_layout.tsx
Labels: bug

#28 WECK-40: Upgrade Expo from SDK 51 to SDK 52
  app.json
  package-lock.json
  package.json
Labels: enhancement, dependencies

#29 WECK-40: Remove .expo folder from repository
  .expo/README.md
  .expo/devices.json
  .expo/types/router.d.ts
  .gitignore
Labels: enhancement
